### ISSUE TITLE
Much needed 

### ISSUE THREAD

**Issue by rajarshikhatua100** [Chooloo/koler#475] opened 2022-08-12 19:28 UTC
call recording is much needed feature now,  is it coming in the app!

**Comment by thisisartman** [comment] 2022-08-28 04:32
If they add this, I'm ditching Google Dialer in an instant.

**Comment by Gottarocket** [comment] 2022-08-28 07:10
An separate option to manage it would be appreciated rather than use filemanager or music player to play or remove it

**Comment by anotherus3r** [comment] 2022-09-05 17:11
Duplicate of #116

**Closed** 2023-01-15 21:03 UTC
Labels: duplicate
