### ISSUE TITLE
App crashes if screen is locked mid-call

### ISSUE THREAD

**Issue by ViktorKahu** [Chooloo/koler#516] opened 2023-03-14 01:39 UTC
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Initiate or answer a phone call.
2. Lock the screen

### Actual behaviour

The phone call continues, but UI crashes. Black screen. If I enter the home screen again and try to open the Koler app, I see nothing but the screen in the screenshot below. Stoppingthe app/clearing cache achieves nothing. There is no way to end the call other than to restart the phone.

### Expected behavior

The opposite of what's stated above.

### Screenshots/Screen recordings

![Screenshot_20230314-122545](https://user-images.githubusercontent.com/125934998/224869903-2746680f-1000-4d40-b3ba-207a57141b01.png)

### Device info
 - Android version/Custom ROM version: Android 13/GrapheneOS
 - Device model: Pixel 7 Pro.

**Comment by roeiedri** [comment] 2023-06-20 17:14
Doesnt happen, probably fixed in recent commits.
If that happens again, please attach some traceback if possible because I can't reproduce the issue :)

**Closed by roeiedri** 2023-06-20 17:14 UTC
Labels: bug

**Comment by ViktorKahu** [comment] 2023-06-20 17:32
...And where can I find a version of the app with these "latest commits"?

This issue was raised in march, the latest available update is from February...?

**Comment by roeiedri** [comment] 2023-06-20 17:54
> ...And where can I find a version of the app with these "latest commits"?
> 
> 
> 
> This issue was raised in march, the latest available update is from February...?

Will soon upload a new release with all the changes

**Comment by ViktorKahu** [comment] 2023-06-20 18:23
Thanks :)
